# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.destroy_all
Item.destroy_all


Category.create(name: "stones")
Item.create([
    {name: "Clear Quartz", quantity: 15, price: 10.00, description: "This crystal is considered a “master healer.” It’s said to amplify energy by absorbing, storing, releasing, and regulating it. It’s also said to aid concentration and memory. Physically, clear crystals are claimed to help stimulate the immune system and balance out your entire body. This stone is often paired with others like rose quartz to aid and enhance their abilities.", image_url: "https://www.healingcrystals.com/images/Specimen---Clear-Quartz-Cathedral-Point-18-Himalayan-01.jpg", category_id: 1},
    {name: "Rose Quartz", quantity: 20, price: 10.00, description: "This crystal is said to help restore trust and harmony in all different kinds of relationships while improving their close connections. It’s also claimed to help provide comfort and calm during times of grief. It isn’t all about other people, though. Rose quartz is said to also encourage love, respect, trust, and worth within one’s self.", image_url: "https://cdn.shopify.com/s/files/1/0273/4214/3566/files/Untitled_design_-_2020-06-30T133217.538.jpg?v=1593520346", category_id: 1},
    {name: "Jasper", quantity: 5, price: 10.99, description: "This smooth crystal is known as the “supreme nurturer.” It’s said to empower the spirit and support you through times of stress by preparing you to fully “show up.” It’s claimed to protect you from and absorb negative vibes while promoting courage, quick thinking, and confidence.", image_url: "https://www.mindat.org/imagecache/9a/94/06528540014972375133274.jpg", category_id: 1},
    {name: "Obsidian", quantity: 12, price: 9.00, description: "An intensely protective stone, obsidian is said to help form a shield against physical and emotional negativity. It’s also said to help get rid of emotional blockage and promote qualities of strength, clarity, and compassion to help find your true sense of self. For your physical body, it may aid in digestion and detoxification while potentially helping reduce pain and cramps.", image_url: "https://m.media-amazon.com/images/I/81RiSdQFQ0L._SL1500_.jpg", category_id: 1},
    {name: "Amethyst", quantity: 32, price: 11.00, description: "This purple stone is said to be incredibly protective, healing, and purifying. It’s claimed it can help rid the mind of negative thoughts and bring forth humility, sincerity, and spiritual wisdom. It’s also said to help promote sobriety. Sleep is another claimed benefit of this stone, from supposedly aiding in insomnia relief to understanding dreams. Physically, it’s said to boost hormone production, cleanse blood, and relieve pain and stress.", image_url: "https://images-na.ssl-images-amazon.com/images/I/81undnXxqOL._AC_SL1500_.jpg", category_id: 1},
    {name: "Moonstone", quantity: 7, price: 12.50, description: "Known for “new beginnings,” moonstone is said to encourage inner growth and strength. When starting fresh, this stone is purported to also soothe those uneasy feelings of stress and instability so you’re able to move forward successfully. It’s also claimed to promote positive thinking, intuition, and inspiration while bringing forth success and good fortune.", image_url: "https://cdn.shopify.com/s/files/1/0159/0942/1110/products/moonstonestone-tumbledstones-energymuse.png?v=1572017543", category_id: 1},
    {name: "Citrine", quantity: 22, price: 10.00, description: "This stone is said to help you release negative traits from your life like fear, and in turn help encourage optimism, warmth, motivation, and clarity. It’s also claimed to enhance mindful qualities, like creativity and concentration.", image_url: "https://www.learnreligions.com/thmb/dykdK-DqZmQ8w3oxS97jS76z9f8=/1601x1200/filters:fill(auto,1)/gi-citrine-56a46b4b3df78cf772825966.jpg", category_id: 1},
    {name: "Tiger's Eye", quantity: 16, price: 7.45, description: "If you’re in need of a power or motivation boost, this golden stone may be for you. It’s said to help rid your mind and body of fear, anxiety, and self-doubt. This can be beneficial for career aspirations or even matters of the heart. Tiger’s eye is also said to help guide you to harmony and balance to help you make clear, conscious decisions.", image_url: "https://meanings.crystalsandjewelry.com/wp-content/uploads/2020/04/Tigers-Eye.jpg", category_id: 1},
    {name: "Bloodstone", quantity: 8, price: 8.75, description: "This powerful healing stone lives up to its name. Bloodstone is claimed to help cleanse the blood by drawing off bad environmental energies and improving circulation. Mindfully speaking, it encourages selflessness, creativity, and idealism while helping you live within the current moment. It’s also said it can also help you rid yourself of feelings of irritability, aggressiveness, and impatience.", image_url: "https://cdn.shopify.com/s/files/1/0273/4214/3566/files/Untitled_design_-_2020-09-29T113103.327.jpg?v=1601375470", category_id: 1},
    {name: "Turquoise", quantity: 2, price: 11.00, description: "This blue crystal has powers that are said to help heal the mind, body, and soul. Generally speaking, it’s seen as a good luck charm that can help balance your emotions while finding your spiritual groundings. When it comes to the body, it’s said to benefit the respiratory, skeletal, and immune system.", image_url: "https://images-na.ssl-images-amazon.com/images/I/71kQPWfADzL._AC_UL1200_.jpg", category_id: 1},
])


Category.create(name: "herbs")
Item.create([
    {name: "Basil", quantity: 13, price: 1.99, description: "Uses span from protection to love to wealth to exorcisms. Also a delicious herb to use when cooking.", image_url: "https://cdn.shopify.com/s/files/1/0156/0137/products/Basil_plant_1280x960_0fc95446-605c-49e3-aa42-c6f3a171b8ae.jpg", category_id: 2},
    {name: "Rosemary", quantity: 20, price: 1.99, description: "Execellect for purification, lust and love, good health, preventing nightmares, and all kinds of sea witchery.", image_url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/02/Rosemary-sprig-7d96e10.jpg?quality=90&resize=960,872", category_id: 2},
    {name: "Lavender", quantity: 54, price: 2.99, description: "Most often used for healing, love, protection, peace, purification, and sleep. Also good for any mental health needs.", image_url: "https://cdn.shopify.com/s/files/1/0156/0137/products/Lavender_plant_1200x960_c5a8afe8-38a9-4679-8769-1c0805dd5aec.jpg", category_id: 2},
    {name: "Chamomile", quantity: 1, price: 2.99, description: "Primarily used in love, healing, and stress reducing spells. Can also be used for luck and gambling.", image_url: "https://www.rainshadowlabs.com/assets/images/chamomile.jpg", category_id: 2},
    {name: "Thyme", quantity: 19, price: 1.99, description: "The best herb for social situations. It attracts loyalty, affection, and a good reputation. Bathe in an infusion of thyme for constant flow of money.", image_url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/02/Thyme-sprig-96aeb6f.jpg?quality=90&resize=960,872", category_id: 2},
    {name: "Cinnamon", quantity: 27, price: 1.00, description: "Ideal for prosperity and success, protection, love, and all spells related to the spiritual self.", image_url: "https://cdn.diabetesselfmanagement.com/2006/10/iStock_000007214835Small.jpg", category_id: 2},
    {name: "Peppermint", quantity: 20, price: 1.00, description: "A favorite herb for the treatment of digestive issues, this herb is ideal for cleansing and protecting. Also a great addition to any luck spell.", image_url: "https://cdn.shopify.com/s/files/1/0156/0137/products/Peppermint_plant_1200x960_94879717-b93f-4eb2-bb7c-571eddd6f2a5.jpg", category_id: 2},
    {name: "Rose", quantity: 50, price: 3.50, description: "The symbol for beauty, marriage, sexuality, devine love, and all kinds of relationships.", image_url: "https://images.squarespace-cdn.com/content/v1/54cebd23e4b02ea7650b9922/1425328387631-443D1VUYBD6XPE8JOIJN/ke17ZwdGBToddI8pDm48kNjiCHVEPYLDIj_BelyebhRZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpy8Hbx50_ibXIce5AuCUz8zXyTJo2BazKHxQNoT87g6tyFvnO_J9aMdJe4oiOvPKNo/rose.png?format=1500w", category_id: 2},
    {name: "Cayanne Pepper", quantity: 34, price: 1.99, description: "Something with a bit of bite that every witch needs. This spice does well as a cursing or banishing agent, or as an addition to any spell to speed up results.", image_url: "https://cdn.shopify.com/s/files/1/1068/6100/products/cayennepepper_1024x1024.jpg?v=1448195713", category_id: 2},
    {name: "Mugwort", quantity: 5, price: 4.25, description: "Used in spells for divination, astral travel, working with the spiritual realm, and recieving prophetic dreams.", image_url: "https://www.gardeningknowhow.com/wp-content/uploads/2014/06/mugwort.jpg", category_id: 2},
])


Category.create(name: "candles")
Item.create([
    {name: "Red Chime", quantity: 10, price: 1.00, description: "Passion, Fire, Strength, Power, Motivation, Desire, Ambition, Business Deals, Confrontation, Courage, Self Esteem", image_url: "https://www.100candles.com/res/items/3433/lg_item_3433_1.jpg", category_id: 3},
    {name: "Orange Chime", quantity: 5, price: 1.00, description: "Relieving Depression, Sealing Spells, Increasing Opportunities, Mental Alertness, Kindness, Harvest, Strength, Dominance, Legal Matters, Happiness", image_url: "https://www.100candles.com/res/items/8928/lg_item_8928_1.jpg", category_id: 3},
    {name: "Yellow Chime", quantity: 52, price: 1.00, description: "Healing, Friendship, Productivity, Creativity, Self Esteem, Humility, Intellect, Removing Negative Thoughts, Sun Energy", image_url: "https://www.100candles.com/res/items/3435/lg_item_3435_1.jpg", category_id: 3},
    {name: "Green Chime", quantity: 25, price: 1.00, description: "Prosperity in matters of the heart, Finances, Increasing Trust, Rebirth, Career, Money, Employment, Fertility, Courage to Change, Relationship stability, Partnerships, New Beginnings, Grounding, Artistic Abilities, Luxury, Social Activity", image_url: "https://www.100candles.com/res/items/8937/lg_item_8937_1.jpg", category_id: 3},
    {name: "Blue Chime", quantity: 17, price: 1.00, description: "Patience, Wisdom, Wealth, Joy, Calming the Mind, Finding Peace, Learning and Growth, Introspection, Removing Confusion, Clarity, Forecasting, Finding Truth", image_url: "https://www.100candles.com/res/items/3434/lg_item_3434_1.jpg", category_id: 3},
    {name: "Purple Chime", quantity: 36, price: 1.00, description: "Clairvoyance, Emotional Pain Release, Spiritual Protection, Increasing Psychic Powers, Communication with Spirits, Intelligence, Memory, Ambition, Forgiveness, Healing Wounded Pride", image_url: "https://www.100candles.com/res/items/3432/lg_item_3432_1.jpg", category_id: 3},
    {name: "White Chime", quantity: 50, price: 1.00, description: "Protection, Safety, Enlightenment, Inviting Guides or Spirits, Connection to your Higher Self, Transformation, Freedom, Focus, Initiation, Health", image_url: "https://www.100candles.com/res/items/8930/lg_item_8930_1.jpg", category_id: 3},
    {name: "Black Chime", quantity: 43, price: 1.00, description: "Balance, Protection, Truth, Divination, Absorbing Energies, Stability, Binding, Manifestation, Accepting Limits, Overcoming Obstacles, Material Gain, Sacrifice ", image_url: "https://www.100candles.com/res/items/8931/lg_item_8931_1.jpg", category_id: 3},
    {name: "Gold Chime", quantity: 24, price: 1.00, description: "Money, Luck, Wealth, Prosperity", image_url: "https://www.100candles.com/res/items/8933/lg_item_8933_1.jpg", category_id: 3},
    {name: "Silver Chime", quantity: 15, price: 1.00, description: "Psychic Awareness, Divination, Secrets, Finding Hidden Thoughts", image_url: "https://www.100candles.com/res/items/8932/lg_item_8932_1.jpg", category_id: 3},
])

